language: go
os: linux
dist: focal
go:
  - 1.16.x
script:
  - make lint
  - make test
  - make testacc
deploy:
  - provider: script
    script: make gorelease
    on:
      tags: true
      all_branches: true
